version: 2.1
commands:
  install_deps:
    steps:
      - run:
          name: Install dependencies
          command: |
            npm install --prefix src/

jobs:
  ci-build:
    docker:
      - image: circleci/node:lts
    environment:
      JEST_JUNIT_OUTPUT_DIR: test-output
    steps:
      - checkout 
      - install_deps
      - run:
          name: run unit tests
          command: |
            npm run test-unit --prefix src/
            mkdir -p test-output
  pack:
    docker:
      - image: circleci/node:lts
    environment:
      NODE_ENV: production
    steps:
      - checkout
      - install_deps
      - store_artifacts:
          path: ./
  sast:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Install NodeJsScan
          command: |
            sudo apt update
            sudo apt install python3-pip
            pip3 install nodejsscan
      - run:
          name: Run NodeJsScan
          command: |
            nodejsscan -d ./src/

workflows:
  build-and-packge:
    jobs:
      - ci-build
      - sast:
          requires:
            - ci-build
      - pack:
          requires:
            - ci-build
          filters:
            branches:
              only:
                - main
            