version: 2.1
commands:
  install_deps:
    steps:
      - run:
          name: Install dependencies
          command: |
            npm install --prefix src/

jobs:
  ci-build:
    docker:
      - image: circleci/node:lts
    environment:
      JEST_JUNIT_OUTPUT_DIR: test-output
    steps:
      - checkout 
      - install_deps
      - run:
          name: run unit tests
          command: |
            npm run test-unit --prefix src/
            mkdir -p test-output
  integration-tests:
    docker:
      - image: circleci/node:lts
      - image: mongo:4.0
    steps:
      - checkout
      - install_deps
      - run:
          name: Integration test
          command: |
            mkdir integration-test
            npm run test-integration --prefix src/
          when: always
      - store_test_results:
          path: src/integration-test
      - store_artifacts:
          path: src/integration-test
  sast:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Install NodeJsScan
          command: |
            sudo apt update
            sudo apt install python3-pip
            pip3 install nodejsscan
      - run:
          name: Run NodeJsScan
          command: |
            nodejsscan -d ./src/ -o sast-output.json
      - store_artifacts:
          path: sast-output.json
      - run:
          name: Parse sast report
          command: |
            # exit with a non-zero exit code if there are any security issues
            exit $(cat sast-output.json | jq .total_count.sec)
  pack:
    docker:
      - image: circleci/node:lts
    environment:
      NODE_ENV: production
    steps:
      - checkout
      - install_deps
      - run:
          name: Packing artifacts
          command: |
            cd src/
            npm pack
      - store_artifacts:
          path: ./src/simpletodoapp-1.0.0.tgz

workflows:
  build-and-packge:
    jobs:
      - ci-build
      - integration-tests:
          requires:
            - ci-build
      - sast:
          requires:
            - ci-build
      - pack:
          requires:
            - ci-build
          filters:
            branches:
              only:
                - main
            